#!/usr/bin/env bash
# This script processes Apache-style log data from standard input.
# It identifies unique combinations of IP addresses and HTTP status codes
awk '{count[$1" "$9]++} END {for (key in count) printf "%6d %s\n", count[key], key}' | sort -rn
