#!/usr/bin/env bash
# Bash script that writes 'I am alive!' indefinitely to '/tmp/my_process' file

# Trap cleanup if needed in future, but right now keep it simple
while true; do
	    echo "I am alive!" >> /tmp/my_process
	        sleep 2
	done

